[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pap_spinel"
version = "0.1.4"
description = "Spinel protocol over UART/TCP for Papouch MCUs."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "VladislavLevitskii", email = "vladlevitskii@gmail.com" }
]
dependencies = [
    "serialx>=1.8.2",
]

[project.urls]
Source = "https://github.com/VladislavLevitskii/pap_spinel"

[tool.hatch.build.targets.wheel]
packages = ["src/pap_spinel"]
